### ISSUE TITLE
Compatibility with new arm-based MacOS

### ISSUE THREAD

**Issue by ericballabene** [histfitter/histfitter#109]
Dear HF experts,

I was wondering if you could make HF compatible with the latest mac operating systems which are being developed for silicon arm processors as plan for the future. I tried the HF installation but it's currently failing (I've attached the log  I get from a tempted local installation). 
[installation_log.txt](https://github.com/histfitter/histfitter/files/7660752/installation_log.txt)
I'm using macOS v12.0.1 with the latest ROOT version, 6.24.06 which is also compatible with my macOS.
Cheers,
  Eric

**Comment by longjon929** [comment]
Hi @ericballabene,

I have no experience with cross-platform compatibility.  So I could be wrong here, but from the warnings in your log file it sounds like there are functions missing on the ROOT library being compiled against.  Does ROOT::Math::normal_cdf(double, double, double) exist in your ROOT install?  If I had to guess, the linker isn't finding your ROOT libraries.

Have you modified makefile.arch?  I don't see arm64 or aarch64, so I assume you'd need to add any special options in a new if statement.  I'm surprised you didn't get an error because of this line:
ifeq ($(CXX),)
$(error $(ARCH) invalid architecture)
endif


Given there are very few people who contribute, I imagine we'd have to rely on someone like you with a platform to test on to make the necessary changes.

Best,
Jonathan


Example from log:
> 3 warnings generated.
> Making shared library: ../lib/libSusyFitter.so
> Undefined symbols for architecture arm64:
>   "**ROOT::Math::normal_cdf**(double, double, double)", referenced from:
>       RooStats::get_Pvalue(RooStats::HypoTestInverterResult const*, bool) in StatTools.o
>   "ROOT::Math::MinimizerOptions::DefaultStrategy()", referenced from:
>       RooStats::ProfileLikelihoodTestStat::ProfileLikelihoodTestStat(RooAbsPdf&) in HypoTestTool.o
>       RooStats::MaxLikelihoodEstimateTestStat::MaxLikelihoodEstimateTestStat(RooAbsPdf&, RooRealVar&) in HypoTestTool.o
>       RooStats::ProfileLikelihoodTestStat::ProfileLikelihoodTestStat(RooAbsPdf&) in StatTools.o
>       Util::FitPdf(RooWorkspace*, TString, bool, RooAbsData*, TString, bool, TString, bool, TString) in Utils.o
>       Util::doFreeFit(RooWorkspace*, RooDataSet*, bool const&, bool const&, bool, bool, TString) in Utils.o
