### ISSUE TITLE
Add functionality to provide input histos for UserSystematic

### ISSUE THREAD

**Issue by longjon929** [histfitter/histfitter#149]
There was a discussion to add the ability to provide histograms for syst variations. @jeanyvesb9 has volunteered to look into this.

**Comment by jeanyvesb9** [comment]
Hi! I'll be opening a PR today. I have a first draft of this working locally, I'm testing it later today

**Comment by jeanyvesb9** [comment]
Quick question: Is there a reason why the user systematics are normalized on a separate loop after loading all histograms first (https://github.com/histfitter/histfitter/blob/master/python/configManager.py#L1031)? Because to make things a bit simpler with this change, the best way would be to move the `PrepareGlobalNormalization` and `addHistoSys` calls to the `addHistoSysforNoQCD` method (https://github.com/histfitter/histfitter/blob/master/python/configManager.py#L1280)

**Comment by longjon929** [comment]
I can't say as I wasn't around for the design.  I haven't looked deeply at this but it's probably to have all of those various steps in the same place.

**Comment by jeanyvesb9** [comment]
Hi! Sorry it took so long. I just made the PR (#150).

**Comment by longjon929** [comment]
Hello @jeanyvesb9 , thanks!  I'll take a closer look through in the coming days.  Could you describe the workflow with this?  I think I'm not completely following how this allows for external histograms for user systs.  In the past I have loaded all of the the histograms from a backup cache (https://gitlab.cern.ch/longjon/HistFitter/-/blob/strong_2l2j/analysis/strong_2l2j.py#L194) to avoid remaking histograms for various iterations. I'm not sure if that is similar to what your changes are accomplishing?

**Comment by jeanyvesb9** [comment]
Hi @longjon929. Yes, the idea is the same as what was already set up for weight and tree-based systematics, where the prepareHistos.addHisto method HF first attempted to load the histogram from the (backup) cache. That didn't happen for user systematics, and they were always re-created on each run of fitConfig.execute (look at the implementatoipn).

For "userOverallSys", I also had to change the implementation in configManager.addHistoSysforNoQCD, since it was always reading the up/down values from the actual Systematic objects instead of using the histograms (even though the histograms were always first created) in the execution loop, when iterating over all systematics within configManager. addSampleSpecificHists (running sys.PrepareWeightsAndHistos on each sys per sample per channel)

**Comment by longjon929** [comment]
Hi @jeanyvesb9, ok I see.  Thanks for completing that functionality for user systs.  Then I guess the idea is that someone could construct the histcache externally and read that in?  

I think we should still look into updating the Systematic() construction to take in a histogram because this would likely be much easier for people than trying to get the correct naming.

**Comment by jeanyvesb9** [comment]
Oh, absolutely! I'll open another issue for it
